apiVersion: v1
kind: Namespace
metadata:
  name: team-orange
spec: {}
status: {}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: mirantis-labs-aws-cluster
  namespace: team-orange
spec:
  clusterNetwork:
    pods:
      cidrBlocks: [10.244.0.0/16]
    services:
      cidrBlocks: [10.96.0.0/12]
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: K0smotronControlPlane
    name: mirantis-labs-aws-cluster
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: AWSCluster
    name: mirantis-labs-aws-cluster
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: mirantis-labs-aws-cluster
  namespace: team-orange
spec:
  k0sVersion: v1.27.2-k0s.0
  persistence:
    type: emptyDir
  service:
    type: LoadBalancer
    apiPort: 6443
    konnectivityPort: 8132
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSCluster
metadata:
  name: mirantis-labs-aws-cluster
  namespace: team-orange
  annotations:
    cluster.x-k8s.io/managed-by: k0smotron
spec:
  region: eu-central-1
  sshKeyName: jhennig-ssh-key
  network:
    vpc:
      id: vpc-095897d5b42a2181e # Machines will be created in this VPC
    subnets:
      - id: subnet-07d4ba06edf1f25c0 # Machines will be created in this Subnet
        availabilityZone: eu-central-1a
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: mirantis-labs-aws-cluster-md
  namespace: team-orange
spec:
  clusterName: mirantis-labs-aws-cluster
  replicas: 3
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: mirantis-labs-aws-cluster
      pool: ec2-worker-small
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: mirantis-labs-aws-cluster
        pool: ec2-worker-small
    spec:
      clusterName: mirantis-labs-aws-cluster
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: K0sWorkerConfigTemplate
          name: mirantis-labs-aws-cluster-mc
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSMachineTemplate
        name: mirantis-labs-aws-cluster-mt
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: mirantis-labs-aws-cluster-mt
  namespace: team-orange
spec:
  template:
    spec:
      ami:
        # Replace with your AMI ID
        id: ami-04e601abe3e1a910f # Ubuntu 22.04 in eu-central-1 
      instanceType: m5.large
      iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io # Instance Profile created by `clusterawsadm bootstrap iam create-cloudformation-stack`
      cloudInit:
        # Makes CAPA use k0s bootstrap cloud-init directly and not via SSM
        # Simplifies the VPC setup as we do not need custom SSM endpoints etc.
        insecureSkipSecretsManager: true
      subnet:
        # Make sure this matches the failureDomain in the Machine, i.e. you pick the subnet ID for the AZ
        id: subnet-07d4ba06edf1f25c0
      additionalSecurityGroups:
        - id: sg-0820c3a5d09a3f97c # Needs to be belong to the subnet
      sshKeyName: jhennig-key
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfigTemplate
metadata:
  name: mirantis-labs-aws-cluster-mc
  namespace: team-orange
spec:
  template:
    spec:
      version: v1.27.2+k0s.0
      # More details of the worker configuration can be set here